### ISSUE TITLE
Record view breaks after a record is rejected from an ingest

### ISSUE THREAD

**Issue by kspurgin** [trln/trln-ingest#45]
At some point UNC ingested UNCb9063164

It was successfully indexed in Solr: 
https://query.discovery.trln.org/trlnbib/get?id=UNCb9063164

Today this record was included in an ingest package I sent through and caused an error because in the meantime, someone has deleted the title field from our catalog (yay?).
https://ingest.discovery.trln.org/transactions/48160

https://ingest.discovery.trln.org/record/search?id=UNCb9063164 now returns "We're sorry, but something went wrong." 

My expectation would be to see the representation of the last successfully-ingested version of this record at that URL.

This raises questions for me like: if I sent this ID through as a delete, does Spofford still know it exists enough to handle the deletion properly?

**Comment by adjam** [comment]
Deleted records should still be viewable via the interface, just this one isn't because there's no resource type on it so the UI blows up trying to show that to you.  I'll make the UI handle this better, but you should be OK deleting the record.

**Comment by kspurgin** [comment]
The record has been deleted. Thanks.

**Comment by adjam** [comment]
closing as this has had work to address it and there is no way to check this particular record.
