### ISSUE TITLE
Document view UI tweaks

### ISSUE THREAD

**Issue by adjam** [trln/trln-ingest#46]
show last updated date on the document
remove useless analysis document serialization
show argot serialization by default
remove identifiers from header, show resource type, access type, and physical media
show record data source
show virtual collections

**Comment by kspurgin** [comment]
I'm thinking it's helpful to see at the top: 

* The major facet values for limiting and access
  * access_type
  * available
  * resource_type
  * physical_media
  * language
* Key fields for initial categorizing of frequent troubleshooting diagnosis/paths and/or which flag that the record is special in some way
  * record_data_source
  * institution
  * virtual_collection
  * rollup_id

UNC perspective: local_id does not need to be displayed at the top under id. Anybody looking at the id in this interface knows how to take the prefix off to get our local id. 

Thanks!
