### ISSUE TITLE
Multiple Asserts in Test Code

### ISSUE THREAD

**Issue by Talismanic** [trln/trln-ingest#62]
Greetings,
I am an engineer who is interested in infrastructure as code testing. Currently, I am looking for testing anti-patterns in iac test scripts. I noticed multiple asserts are occurring in test instances which can lead to unwanted scenarios in Ansible Testing. For example, in the case of multiple asserts, ansible will stop running the playbook if the first assert fails. So to check whether the second assert work, we will have to ensure the first assert always passes. I think this is an anti-pattern of testing practices.

So I have the following query:

Do you agree that this is an IaC testing anti-pattern?
Do you want to fix this?

Any feedback is appreciated.

Source File:
https://github.com/trln/trln-ingest/blob/master/ansible/roles/rvm.ruby/tests/assertions.yml

**Comment by adjam** [comment]
Thanks for your interest!The tests to which you refer are in an imported role, and do not belong specifically to this repository.

**Comment by Talismanic** [comment]
Thanks for the lead. 

However, it will be great help if I get your personal opinion on this matter. In principle, do you agree that we should not use multiple asserts in a test task in ansible?
