### ISSUE TITLE
centos/7 box does not sync correctly between host and VM

### ISSUE THREAD

**Issue by corylown** [trln/trln-ingest#9]
I think I can fix this by using a different centos 7 box.

geerlingguy/centos7 is suggested in this thread:

https://github.com/CentOS/sig-cloud-instance-build/issues/27

**Comment by adjam** [comment]
@corylown did you install the `vagrant-vbguest` vagrant plugin?  I'm not otherwise opposed to using a different box.

**Comment by corylown** [comment]
@adjam I did try installing that. But I'll give it another try before proposing moving to a different box.

**Comment by adjam** [comment]
According to https://github.com/CentOS/sig-cloud-instance-build/pull/28/commits/ab1d40dc2498ec974bf55164e62b93793fab6ec8 it seems that adding bzip2 to the image is what makes the difference.

**Comment by corylown** [comment]
@adjam So, I think part of my confusion was that both /vagrant and ~/synced appear to show the same shared directory on the VM, but only ~/synced actually syncs content between the VM and the host. Closing the issue.

**Comment by adjam** [comment]
It might make sense to resurrect this issue or create a new one to make the mount point more sensible, in that case.  Vagrant tends to mount the directory containing the Vagrantfile as the home directory, but during development I wanted the home directory to be mostly empty, so Spofford can create directories there and they wouldn't have to go into .gitignore.  In mounting . under ~/synced, though, it gets confusing.  I'm open to suggestions.

**Comment by corylown** [comment]
My understanding is that the standard mount point for the shared directory in the VM is /vagrant

**Comment by adjam** [comment]
Which is of course correct.  Never mind =)

**Comment by corylown** [comment]
@adjam @queryluke I propose then that we remove the ~/synced directory (unless there is a reason it's needed that I don't know about) and just use the standard synced directory mount point of /vagrant. If that's OK with everyone I will update the Vagrantfile and references to the ~/synced dir in the setup and readme.

**Comment by queryluke** [comment]
I have no objections
